spring:
  application:
    name: trading-application
  server:
    port: 8080
  cache:
    type: simple

  # H2 DB configuration
  datasource:
    url: jdbc:h2:mem:tradingDB
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create

# To access H2 DB console http://localhost:8080/h2-console
  h2:
    console:
      enabled: true
      path: /h2-console

# OPENAPI Swagger
openapi:
  dev-url: http://localhost:8080
  prod-url: https://www.db.de

# Workflow configuration key
workflow:
  config:
    signal: signal
    actions: actions
    action: action
    params: params
    param:
      name: name
      type: type
      value: value